correction/s5/j4/sebastien/ancient-thicket-43098/config/routes.rb
Rails.application.routes.draw do
 
  get '/', to: 'index#welcomepage'
  post '/', to: 'index#welcomepage'
  get '/contact', to: 'static#contact'
  get '/team', to: 'static#team'
  
  resources :login, only: [:new, :create, :index, :destroy]

  resources :user

  resources :gossip

  resources :city

  resources :button

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/models/city.rb
class City < ApplicationRecord
has_many :users
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user

	validates :title, presence: true, 
	length: { in: 3..14}
	validates :description, presence: true
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/models/user.rb
class User < ApplicationRecord
	has_many :gossips
	belongs_to :city
	has_many :likes
	has_secure_password
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/controllers/button_controller.rb
class ButtonController < ApplicationController
  def new

  end

  def create

  end 
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
  	@city = City.find(params[:id])
  	@gossips = Gossip.all
   end
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  
  before_action :authenticate_user, only: [:create, :edit, :destroy]

 def show
 	
     @num = params[:id]
     @gossips = Gossip.find(@num)
 end

 def new
     @gossip= Gossip.new
 end

 def create
 gossip = Gossip.create(title:params[:title], description:params[:description], user_id: session[:user_id])
 redirect_to ('/')
 end

 def edit

  @gossips = Gossip.find(params[:id])

 end

 def update

    @gossips = Gossip.find(params[:id])
    @gossips.update(gossip_params)
    redirect_to('/')

 end

 def destroy

  @gossips = Gossip.find(params[:id])
   @gossips.destroy
   redirect_to('/')
 end

 private

  def authenticate_user
    unless current_user
      flash[:danger] = "Connecte toi !"
      redirect_to new_login_path
    end
  end

 def gossip_params
params.require(:gossip).permit(:title ,:description)
end
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/controllers/index_controller.rb
class IndexController < ApplicationController

  def welcomepage
  	@gossips = Gossip.all
  end
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  

  end

  def new 

  end 

def create
 
  user = User.find_by(email: params[:email])

  if user && user.authenticate(params[:psw])
    session[:user_id] = user.id
    redirect_to '/'

  else
    puts "--" * 60
  	puts "T'es nul"
  	puts "--" * 60
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
  end
end

  def destroy

   session.delete(:user_id)
   redirect_to '/'

  end
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
 	num = params[:id]
  	@gossips = Gossip.find(num)
  end

  def new

  end 

  def create 
  	
    if City.find_by(name: "params[:city]") == nil 

    puts "@@@@"*60
    @c = City.new(name:params[:city])
    @u = User.new(first_name:params[:first_name], last_name:params[:last_name], age:params[:age], email:params[:email], password:params[:psw], city_id: @c.id)
    @u.save
    puts @u.errors
    puts "@@@@"*60
    redirect_to('/')

  else 

    puts "@@@@"*60
    @cc = City.find_by(name: "params[:city]")
    @u = User.new(first_name:params[:first_name], last_name:params[:last_name], age:params[:age], email:params[:email], password:params[:psw], city_id: @cc.id)
    @u.save
    puts @u.errors
    puts "@@@@"*60
    redirect_to('/')

    end 

  end 

end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/application_helper.rb
module ApplicationHelper
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/button_helper.rb
module ButtonHelper
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/city_helper.rb
module CityHelper
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/gossip_helper.rb
module GossipHelper
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/index_helper.rb
module IndexHelper
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/login_helper.rb
module LoginHelper
	
	def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/static_helper.rb
module StaticHelper
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/user_helper.rb
module UserHelper
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/helpers/welcome_helper.rb
module WelcomeHelper
end

correction/s5/j4/sebastien/ancient-thicket-43098/app/views/index/welcomepage.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Bienvenue sur notre site The Gossip Project !</h1>
    <p class="lead"><center>"Les poucaves a la cave !"</center></p>
  </div>
</div>


  <div class="card-deck">
   <% @gossips.each do |gossip| %> 
    <div class="col-3">
      <div class="card text-center">
  <div class="card-header d-flex justify-content-center">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item">
        <a class="nav-link" href="<%= edit_gossip_path(gossip.id)%>">Edit</a>
          </p>
      </li>
      <li class="nav-item">
        
        <a class= "nav-link"<%= link_to "Voir profil", controller: "user", action:"show", id: gossip.id %> </a>
     </a>
     </li>

  <li class="nav-item">
       <button type="button" class="btn btn-primary"> I Like That <span class="badge badge-light">4</span>
</button>
      </li>

    </ul>
  </div>
  <div class="card-body">
    <h2 class="card-title">"<%= gossip.title %>"</h2>
    <h4 class="card-text"><I>Ecrit par : <%= gossip.user.first_name %></I> </h4>
    <p class="card-text"><%= gossip.description %></p>
    <a href="<%=gossip_path(gossip.id)%>" class="btn btn-light">Voir plus</a>
  </div>
    <% if gossip.user.id == session[:user_id] %>
    <a class ="btn btn-danger" href="<%= gossip_path(gossip.id)%>" data-confirm="Etes vous sur de vouloir supprimer ce Gossip ?" data-method="DELETE">Supprimer</a>
      <% end %>     
  </div>
</div>


    
    <% end %>
 