correction/e-commerce/correction/thp_kitties/config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  resources :products, :path=> "cats" do
    resources :products_avatars, only: [:create]
  end

  resources :users, :path=> "friends", only: [:show, :edit, :update] do
      resources :avatars, only: [:create]
  end

  namespace :admins do
    resources :admin, only: [:index]
    resources :users
    resources :products
    root to: "admin#index"
  end

  resources :carts, only: [:destroy, :create, :update, :show]
  resources :orders,  only: [:index, :create]

  resources :cart_products
  root 'home#index'
  get 'contact', to: 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

correction/e-commerce/correction/thp_kitties/app/models/product.rb
class Product < ApplicationRecord
  validates :price,
        presence: true,
        numericality: {greater_than: 0}
  validates :title,
        presence: true,
        length: { in: 3..30, message: "must be between 3 and 30 characters" }
  validates :description,
        presence: true,
        length: {in: 15..600, message: "must be between 20 and 600 characters"}


  has_many :cart_products, dependent: :destroy
  has_one_attached :avatar
end

correction/e-commerce/correction/thp_kitties/app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController

  def index
    @users = User.all
    @products = Product.all
    @orders = Order.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    product_params = params.permit(:title, :description, :price)

    if @product.update(product_params)
      @product.avatar.attach(params[:avatar])
      flash[:notice] = "The product was successfully modified"
      redirect_to admins_products_path
    else
      render :show
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admins_root_path
  end

 private

  def check_if_admin
    redirect_to root_path unless current_user.try(:admin?)
  end

end

correction/e-commerce/correction/thp_kitties/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:price, :name)
    end
end

correction/e-commerce/correction/thp_kitties/app/helpers/products_helper.rb
module ProductsHelper
end

correction/e-commerce/correction/thp_kitties/app/views/admins/products/edit.html.erb
<%= stylesheet_link_tag "products", media: "all" %>

<%= form_tag url_for(action: 'update'), method: "patch", multipart: true do %>
        <section class="slice slice-lg" id="sct-products">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <!-- Product gallery -->
                        <div class="mb-5 imgProd">
                            <%if @product.avatar.attached?%>
                                <%= link_to product_path(@product.id) do  %>
                                    <%= image_tag @product.avatar, alt: 'cat', height: 550, width: 550%>
                                <% end %>
                            <%else%>
                                <%= link_to product_path(@product.id) do  %>
                                    <img alt="Image placeholder" src="/assets/img/brand/logo_1.png" class="img-fluid">
                                 <% end %>
                            <%end%>
                        </div>

                    </div>
                    <div class="col-lg-6">
                        <form class="pl-lg-4">

                            <div class="field">
                                <%= file_field_tag :avatar%>
                            </div>

                            <!-- Product title -->
                            <%= label_tag 'Title'%>
                            <%= text_field_tag :title, @product.title, class:'form-control', placeholder: @product.title, style: "width: auto"%>


                            <!-- Product description -->
                            <div class="mt-4">
                                <small class="text-dark font-weight-bold d-block mb-2">Description:</small>
                                 <%= text_area_tag :description, @product.description, class:'form-control text-sm lh-150', placeholder: @product.description, style: "width: auto"%>
                            </div>

                            <!-- Size -->
                            <div class="mt-4">
                                <small class="d-block font-weight-bold text-dark mb-2">Price:</small>
                                <%= text_field_tag :price, @product.price, class:'form-control text-sm lh-150', placeholder: @product.price, style: "width: auto"%>
                            </div>

                            <!-- Color -->
                            <div class="mt-4">
                                <small class="d-block font-weight-bold text-dark mb-2">Color:</small>
                                <div class="d-flex">
                                    <div class="custom-color">
                                        <input id="color-1" name="size" type="radio">
                                        <label for="color-1" class="rounded-circle" style="background: #59ad46;"></label>
                                    </div>
                                    <div class="custom-color">
                                        <input id="color-2" name="size" type="radio">
                                        <label for="color-2" class="rounded-circle" style="background: #04050a;"></label>
                                    </div>
                                    <div class="custom-color">
                                        <input id="color-3" name="size" type="radio">
                                        <label for="color-3" class="rounded-circle" style="background: #62aedd;"></label>
                                    </div>
                                    <div class="custom-color">
                                        <input id="color-4" name="size" type="radio">
                                        <label for="color-4" class="rounded-circle" style="background: #e84385;"></label>
                                    </div>
                                </div>
                            </div>

                            <!-- Quantity -->
                            <div class="mt-4">
                                <div class="d-flex">
                                    <%= link_to 'Back to admin index', admins_products_path,    :class => "btn btn-primary ml-3"  %>
                                </div>
                            </div>

                            <!-- Product info -->
                            <div class="mt-4">
                                <small class="d-block font-weight-bold text-dark">Maintaining</small>
                                <ul class="list-unstyled list-icon">
                                    <li class="text-sm py-1">
                                        <i class="fas fa-tshirt mr-3"></i>Exterior: 98% Furr, 2% Claws
                                    </li>
                                    <li class="text-sm py-1">
                                        <i class="fas fa-air-freshener mr-3"></i>Try not to put your cat in the laundry machine too often, manual wash prefered
                                    </li>
                                    <li class="text-sm py-1">
                                        <i class="fas fa-charging-station mr-3"></i>Iron up to 110&deg;C/230&deg;F
                                    </li>
                                </ul>
                            </div>
                        </form>
                    </div>
                </div>
                <%= submit_tag "Modify", class: "btn btn-primary" %>
            </div>
        </section>


    </main>
<% end %>

correction/e-commerce/correction/thp_kitties/app/views/admins/products/index.html.erb
<%= render 'admins/admin/admin_page' %>

<div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Image</th>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col" class="text-center"><i class="fas fa-sort ml-2"></th>
        </tr>
      </thead>
      <tbody>
        <% @products.order(:id).each do |product| %>
            <tr>
              <td> <%= product.id %></td>
              <%if product.avatar.attached?%>
                <td><%= image_tag product.avatar, alt: 'Image placeholder', class: "mr-3", width: 50, height: 50  %></td>
              <%else%>
                <td><%= image_tag "/assets/img/brand/logo_1.png", alt: 'Image placeholder', class: "mr-3", width: 50, height: 50  %></td>
              <%end%>
              <td><%= product.title %></td>
              <td><%= product.description %></td>
              <td  class="text-center">
                <%= link_to '<i class="far fa-eye"></i>'.html_safe, edit_admins_product_path(product.id), class: "text-decoration-none "  %>
                <a href="<%= admins_product_path(product.id) %>" data-confirm="Etes-vous sûr ?" data-method="DELETE"><i class="fas fa-trash-alt"></i></a>
              </td>
            </tr>
        <% end %>



      </tbody>
    </table>
</div>

correction/e-commerce/correction/thp_kitties/app/views/admins/products/show.html.erb
<%= stylesheet_link_tag "products", media: "all" %>

<%= form_tag url_for(action: 'update'), method: "patch", multipart: true do %>
        <section class="slice slice-lg" id="sct-products">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <!-- Product gallery -->
                        <div class="mb-5 imgProd">
                            <%if @product.avatar.attached?%>
                                <%= link_to product_path(@product.id) do  %>
                                    <%= image_tag @product.avatar, alt: 'cat', height: 550, width: 550%>
                                <% end %>
                            <%else%>
                                <%= link_to product_path(@product.id) do  %>
                                    <img alt="Image placeholder" src="/assets/img/brand/logo_1.png" class="img-fluid">
                                 <% end %>
                            <%end%>
                        </div>

                    </div>
                    <div class="col-lg-6">
                        <form class="pl-lg-4">

                            <div class="field">
                                <%= file_field_tag :avatar%>
                            </div>

                            <!-- Product title -->
                            <%= label_tag 'Title'%>
                            <%= text_field_tag :title, @product.title, class:'form-control', placeholder: @product.title, style: "width: auto"%>


                            <!-- Product description -->
                            <div class="mt-4">
                                <small class="text-dark font-weight-bold d-block mb-2">Description:</small>
                                 <%= text_area_tag :description, @product.description, class:'form-control text-sm lh-150', placeholder: @product.description, style: "width: auto"%>
                            </div>

                            <!-- Size -->
                            <div class="mt-4">
                                <small class="d-block font-weight-bold text-dark mb-2">Price:</small>
                                <%= text_field_tag :price, @product.price, class:'form-control text-sm lh-150', placeholder: @product.price, style: "width: auto"%>
                            </div>

                            <!-- Color -->
                            <div class="mt-4">
                                <small class="d-block font-weight-bold text-dark mb-2">Color:</small>
                                <div class="d-flex">
                                    <div class="custom-color">
                                        <input id="color-1" name="size" type="radio">
                                        <label for="color-1" class="rounded-circle" style="background: #59ad46;"></label>
                                    </div>
                                    <div class="custom-color">
                                        <input id="color-2" name="size" type="radio">
                                        <label for="color-2" class="rounded-circle" style="background: #04050a;"></label>
                                    </div>
                                    <div class="custom-color">
                                        <input id="color-3" name="size" type="radio">
                                        <label for="color-3" class="rounded-circle" style="background: #62aedd;"></label>
                                    </div>
                                    <div class="custom-color">
                                        <input id="color-4" name="size" type="radio">
                                        <label for="color-4" class="rounded-circle" style="background: #e84385;"></label>
                                    </div>
                                </div>
                            </div>

                            <!-- Quantity -->
                            <div class="mt-4">
                                <div class="d-flex">
                                    <%= link_to 'Back to admin index', admins_products_path,    :class => "btn btn-primary ml-3"  %>
                                </div>
                            </div>

                            <!-- Product info -->
                            <div class="mt-4">
                                <small class="d-block font-weight-bold text-dark">Maintaining</small>
                                <ul class="list-unstyled list-icon">
                                    <li class="text-sm py-1">
                                        <i class="fas fa-tshirt mr-3"></i>Exterior: 98% Furr, 2% Claws
                                    </li>
                                    <li class="text-sm py-1">
                                        <i class="fas fa-air-freshener mr-3"></i>Try not to put your cat in the laundry machine too often, manual wash prefered
                                    </li>
                                    <li class="text-sm py-1">
                                        <i class="fas fa-charging-station mr-3"></i>Iron up to 110&deg;C/230&deg;F
                                    </li>
                                </ul>
                            </div>
                        </form>
                    </div>
                </div>
                <%= submit_tag "Modify", class: "btn btn-primary" %>
            </div>
        </section>


    </main>
<% end %>